/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#030303",
        surface: "#080808",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#0a0a0a",
        "surface-container": "#111111",
        "surface-container-high": "#181818",
        "surface-container-highest": "#222222",
        "surface-bright": "#2a2a2a",
        "surface-variant": "#222222",
        "on-surface": "#e2e8f0",
        "on-surface-variant": "#94a3b8",
        "outline": "#334155",
        "outline-variant": "#1e293b",
        "primary-container": "#00e5ff",
        "primary-fixed": "#00e5ff",
        "primary-fixed-dim": "#00b3cc",
        "on-primary": "#002b33",
        "on-primary-container": "#cffafe",
        "secondary-container": "#a855f7",
        "secondary-fixed": "#d8b4fe",
        "on-secondary-container": "#e9d5ff",
        "tertiary-container": "#e81cff",
        "on-tertiary-container": "#fce7f3",
        "accent-blue": "#3b82f6",
        "on-accent-blue": "#1e3a8a",
        "accent-purple": "#BC00FF",
        "accent-orange": "#FF8A00",
        "accent-green": "#00FF88",
        "accent-red": "#FF3366",
      },
      fontFamily: {
        display: ["'Space Grotesk'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        code: ["'JetBrains Mono'", "monospace"],
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(90deg, #00e5ff, #a855f7)',
        'synth-gradient': 'linear-gradient(90deg, #00e5ff, #a855f7, #e81cff)',
        'cyan-gradient': 'linear-gradient(135deg, #00e5ff 0%, #00b3cc 100%)',
        'purple-gradient': 'linear-gradient(135deg, #a855f7 0%, #7c3aed 100%)',
        'scanlines': 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0, 229, 255, 0.03) 2px, rgba(0, 229, 255, 0.03) 4px)',
        'grid-pattern': 'linear-gradient(rgba(255, 255, 255, 0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255, 255, 255, 0.03) 1px, transparent 1px)',
        'grid-pattern-cyan': 'linear-gradient(rgba(0,229,255,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(0,229,255,0.04) 1px, transparent 1px)',
        'noise-overlay': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.05'/%3E%3C/svg%3E\")",
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-mesh': 'linear-gradient(135deg, #030303 0%, #0a1628 50%, #030303 100%)',
      },
      boxShadow: {
        'glow-primary': '0 0 15px rgba(0, 229, 255, 0.25), 0 0 40px rgba(0, 229, 255, 0.1)',
        'glow-ambient': '0 0 50px 10px rgba(168, 85, 247, 0.08)',
        'glow-intense': '0 0 25px 5px rgba(0, 229, 255, 0.4)',
        'glow-purple': '0 0 15px rgba(168, 85, 247, 0.4), 0 0 40px rgba(168, 85, 247, 0.15)',
        'glow-pink': '0 0 15px rgba(232, 28, 255, 0.4)',
        'glow-green': '0 0 25px 5px rgba(0, 255, 136, 0.3)',
        'glow-orange': '0 0 25px 5px rgba(255, 138, 0, 0.3)',
        'glow-red': '0 0 25px 5px rgba(255, 51, 102, 0.3)',
        'inner-cyan': 'inset 0 0 20px rgba(0, 229, 255, 0.05)',
        'neon-border': '0 0 0 1px rgba(0, 229, 255, 0.3), 0 0 20px rgba(0,229,255,0.15)',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'grid-scroll': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(40px)' },
        },
        'scan': {
          '0%': { top: '-10%' },
          '100%': { top: '110%' },
        },
        'beam': {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh)', opacity: '0' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(0, 229, 255, 0.2)' },
          '50%': { boxShadow: '0 0 40px rgba(0, 229, 255, 0.5)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'glitch': {
          '0%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 2px)' },
          '40%': { transform: 'translate(-2px, -2px)' },
          '60%': { transform: 'translate(2px, 2px)' },
          '80%': { transform: 'translate(2px, -2px)' },
          '100%': { transform: 'translate(0)' },
        },
        'typewriter': {
          'from': { width: '0' },
          'to': { width: '100%' },
        },
        'gradient-bg': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'light-sweep': {
          '0%': { transform: 'translateX(-100%) skewX(-15deg)' },
          '100%': { transform: 'translateX(200%) skewX(-15deg)' },
        },
        'flicker': {
          '0%, 19%, 21%, 23%, 25%, 54%, 56%, 100%': { opacity: '1' },
          '20%, 22%, 24%, 55%': { opacity: '0.4' },
        },
        'blink': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'counter': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'heartbeat': {
          '0%, 100%': { transform: 'scale(1)' },
          '10%': { transform: 'scale(1.15)' },
          '20%': { transform: 'scale(1)' },
          '30%': { transform: 'scale(1.1)' },
          '40%': { transform: 'scale(1)' },
        },
        'ping-slow': {
          '0%': { transform: 'scale(1)', opacity: '0.5' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        'reveal-from-left': {
          '0%': { clipPath: 'inset(0 100% 0 0)', opacity: '0' },
          '100%': { clipPath: 'inset(0 0% 0 0)', opacity: '1' },
        },
      },
      animation: {
        marquee: 'marquee 30s linear infinite',
        'grid-scroll': 'grid-scroll 2s linear infinite',
        'scan': 'scan 6s linear infinite',
        'beam': 'beam 4s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'glitch': 'glitch 0.3s linear infinite',
        'typewriter': 'typewriter 2s steps(40) forwards',
        'blink': 'blink 1s step-end infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'counter': 'counter 0.5s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.5s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.5s ease-out forwards',
        'scale-in': 'scale-in 0.4s ease-out forwards',
        'heartbeat': 'heartbeat 2s ease-in-out infinite',
        'gradient-bg': 'gradient-bg 3s ease infinite',
        'light-sweep': 'light-sweep 2s infinite',
        'flicker': 'flicker 4s step-end infinite',
        'ping-slow': 'ping-slow 2s cubic-bezier(0,0,0.2,1) infinite',
        'reveal-from-left': 'reveal-from-left 0.8s ease forwards',
      }
    },
  },
  plugins: [],
}
