// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Badge = __t.object("Badge", {
  id: __t.string(),
  name: __t.string(),
  description: __t.string(),
});
export type Badge = __Infer<typeof Badge>;

export const GameStat = __t.object("GameStat", {
  statId: __t.string(),
  value: __t.string(),
});
export type GameStat = __Infer<typeof GameStat>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  userIdentity: __t.string(),
  username: __t.string(),
  elo: __t.u32(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const MatchLog = __t.object("MatchLog", {
  matchId: __t.string(),
  codeUpdates: __t.string(),
  winnerId: __t.string(),
  loserId: __t.string(),
  timestamp: __t.u64(),
});
export type MatchLog = __Infer<typeof MatchLog>;

export const User = __t.object("User", {
  identity: __t.string(),
  username: __t.string(),
  matchesPlayed: __t.u32(),
  wins: __t.u32(),
});
export type User = __Infer<typeof User>;

export const UserBadge = __t.object("UserBadge", {
  userIdentity: __t.string(),
  badgeId: __t.string(),
  awardedAt: __t.u64(),
});
export type UserBadge = __Infer<typeof UserBadge>;

