// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateOrUpdateUserReducer from "../create_or_update_user_reducer";
import EndMatchReducer from "../end_match_reducer";
import GrantBadgeReducer from "../grant_badge_reducer";
import RecordStatReducer from "../record_stat_reducer";

export type CreateOrUpdateUserParams = __Infer<typeof CreateOrUpdateUserReducer>;
export type EndMatchParams = __Infer<typeof EndMatchReducer>;
export type GrantBadgeParams = __Infer<typeof GrantBadgeReducer>;
export type RecordStatParams = __Infer<typeof RecordStatReducer>;

